// Generated by npm run bundle:reader. Edit index.ts or _shared/validation.ts, then regenerate.
// Paste this entire file into the Supabase dashboard editor as index.ts.

export interface ValidatedAnswer {
  question_number: number
  student_answer: string
  confidence: number
  points?: number
  feedback?: string
}
export interface ValidatedViolation { question_number: number | null; violation: string; confidence: number | null }
const record = (value: unknown): Record<string, unknown> => {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Expected an object.')
  return value as Record<string, unknown>
}
export function validateReadRequest(value: unknown) {
  const input = record(value)
  if (typeof input.sessionId !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(input.sessionId)) throw new Error('A valid session is required.')
  if (typeof input.imageBase64 !== 'string' || input.imageBase64.length < 8 || input.imageBase64.length > Math.ceil(5 * 1024 * 1024 / 3) * 4 || !/^[A-Za-z0-9+/]+={0,2}$/.test(input.imageBase64) || input.imageBase64.length % 4 !== 0) throw new Error('Choose an image smaller than 5 MB.')
  if (input.mimeType !== 'image/jpeg' && input.mimeType !== 'image/png' && input.mimeType !== 'image/webp') throw new Error('Choose a JPEG, PNG, or WebP image.')
  const prefix = atob(input.imageBase64.slice(0, 32))
  const valid = input.mimeType === 'image/jpeg' ? prefix.startsWith('\xff\xd8\xff') : input.mimeType === 'image/png' ? prefix.startsWith('\x89PNG\r\n\x1a\n') : prefix.startsWith('RIFF') && prefix.slice(8,12) === 'WEBP'
  if (!valid) throw new Error('The image format does not match its file type.')
  return { sessionId: input.sessionId, imageBase64: input.imageBase64, mimeType: input.mimeType }
}
export function validateRecognition(value: unknown, questionNumbers: number[]) {
  const input = record(value)
  if (!Array.isArray(input.answers) || input.answers.length > questionNumbers.length) throw new Error('Invalid answers.')
  const expected = new Set(questionNumbers)
  const seen = new Set<number>()
  const answers: ValidatedAnswer[] = input.answers.map((raw: unknown) => {
    const a = record(raw)
    if (typeof a.question_number !== 'number' || !Number.isInteger(a.question_number) || !expected.has(a.question_number) || seen.has(a.question_number)) throw new Error('Invalid or duplicate question number.')
    seen.add(a.question_number)
    if (typeof a.student_answer !== 'string' || a.student_answer.length > 20000) throw new Error('Invalid answer text.')
    const confidence = a.confidence === undefined || a.confidence === null ? 0 : a.confidence
    if (typeof confidence !== 'number' || !Number.isFinite(confidence) || confidence < 0 || confidence > 1) throw new Error('Invalid confidence.')
    if (a.points !== undefined && (typeof a.points !== 'number' || !Number.isFinite(a.points) || a.points < 0)) throw new Error('Invalid points.')
    if (a.feedback !== undefined && (typeof a.feedback !== 'string' || a.feedback.length > 5000)) throw new Error('Invalid feedback.')
    return { question_number: a.question_number, student_answer: a.student_answer, confidence, ...(typeof a.points === 'number' ? { points: a.points } : {}), ...(typeof a.feedback === 'string' ? { feedback: a.feedback } : {}) }
  })
  if (!answers.some((a) => a.student_answer.trim())) throw new Error('No readable answers.')
  for (const n of expected) if (!seen.has(n)) answers.push({ question_number: n, student_answer: '', confidence: 0 })
  const violations = input.rule_violations ?? []
  if (!Array.isArray(violations) || violations.length > 300) throw new Error('Invalid rule checks.')
  const rule_violations: ValidatedViolation[] = violations.map((raw: unknown) => {
    const v = record(raw)
    if (v.question_number !== null && (typeof v.question_number !== 'number' || !expected.has(v.question_number))) throw new Error('Invalid rule question.')
    if (typeof v.violation !== 'string' || !v.violation.trim() || v.violation.length > 1000) throw new Error('Invalid violation.')
    const confidence = v.confidence ?? null
    if (confidence !== null && (typeof confidence !== 'number' || !Number.isFinite(confidence) || confidence<0 || confidence>1)) throw new Error('Invalid rule confidence.')
    return { question_number: v.question_number as number | null, violation: v.violation, confidence: confidence as number | null }
  })
  return { answers, rule_violations }
}

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY') ?? ''
const GEMINI_MODELS = ['gemini-3.5-flash-lite', 'gemini-3.8-flash']

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

type AnswerKind = 'multiple_choice' | 'true_false' | 'identification' | 'coding' | 'essay'

interface KeyItem {
  question_number: number
  question_type?: string | null
  max_points?: number | null
  rubric?: string | null
}

/** How each answer kind should be read. */
const KIND_RULES: Record<AnswerKind, string> = {
  multiple_choice: 'read a single letter (A, B, C, D or E) only — never a word or code',
  true_false: 'read exactly "True" or "False"',
  identification: 'read the written word or short phrase',
  coding: 'read the code VERBATIM, including punctuation and any error text; do not fix or simplify it',
  essay: 'read the full written response',
}

function kindOf(item: KeyItem): AnswerKind {
  const t = item.question_type
  if (t === 'multiple_choice' || t === 'true_false' || t === 'identification' || t === 'coding' || t === 'essay') {
    return t
  }
  return 'identification'
}

/**
 * Build a compact description of the expected answer type per question.
 * Consecutive questions of the same kind are grouped into a range so the model
 * gets a clear "Part" structure and never guesses the type.
 */
function describeKey(keys: KeyItem[]): string {
  if (keys.length === 0) return ''
  const sorted = [...keys].sort((a, b) => a.question_number - b.question_number)
  const ranges: { from: number; to: number; kind: AnswerKind }[] = []
  for (const k of sorted) {
    const kind = kindOf(k)
    const last = ranges[ranges.length - 1]
    if (last && last.kind === kind && k.question_number === last.to + 1) {
      last.to = k.question_number
    } else {
      ranges.push({ from: k.question_number, to: k.question_number, kind })
    }
  }
  return ranges
    .map((r) => {
      const label = r.from === r.to ? `Q${r.from}` : `Q${r.from}–${r.to}`
      return `- ${label}: ${KIND_RULES[r.kind]}`
    })
    .join('\n')
}

function buildPrompt(totalItems: number, keys: KeyItem[], rules: string): string {
  const keyDescription = describeKey(keys)
  const hasEssays = keys.some((k) => kindOf(k) === 'essay')

  const typeInstruction = keyDescription
    ? 'The expected answer type for each question is below. Follow it exactly and IGNORE the numbers printed on the paper — they may restart in each section. Assign the answers in reading order (top to bottom):\n' +
      keyDescription
    : `Read the student's answers for the ${totalItems} questions, in order from top to bottom.`

  const essayInstruction = hasEssays
    ? ' For essay questions, grade against the rubric provided below each question. Return "points" (a number) and a short "feedback" string for each essay answer.'
    : ''

  let rubricBlock = ''
  const essayKeys = keys.filter((k) => kindOf(k) === 'essay')
  if (essayKeys.length > 0) {
    rubricBlock =
      ' Essay rubrics:\n' +
      essayKeys
        .map(
          (k) =>
            `Q${k.question_number} (max ${k.max_points ?? 10} points): ${(k.rubric ?? '').trim() || 'No rubric provided — award points based on overall correctness.'}`,
        )
        .join('\n')
  }

  const rulesPrompt = rules
    ? ' Also check the paper against these rules and list any violations you are CONFIDENT about: "' +
      rules +
      '". Put them in a separate array "rule_violations". Only report a violation when you can clearly see it AND you can confidently identify its question_number; otherwise set question_number to null. Include a "confidence" from 0 to 1 for each violation.'
    : ''

  return (
    `This is a handwritten exam answer sheet with ${totalItems} questions. ` +
    typeInstruction +
    ' ' +
    'For each question, estimate a "confidence" number from 0 to 1 for how sure you are the reading is correct — you MUST include one for EVERY answer. ' +
    'Respond ONLY with a JSON object in this exact format, no extra text: ' +
    '{"answers":[{"question_number":1,"student_answer":"B","confidence":0.95}], "rule_violations":[{"question_number":1,"violation":"erasure detected","confidence":0.8}]}. ' +
    'If an answer is unreadable, use an empty string and confidence 0.0.' +
    essayInstruction +
    rubricBlock +
    rulesPrompt
  )
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })

  if (req.method !== 'POST') return Response.json({ error: 'Use POST.' }, { status: 405, headers: corsHeaders })
  const fail = (error: string, status: number) => Response.json({ error }, { status, headers: corsHeaders })
  const authHeader = req.headers.get('authorization') ?? ''
  if (!/^Bearer \S+$/i.test(authHeader)) return fail('Please sign in to check papers.', 401)
  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
  const anonKey = Deno.env.get('SUPABASE_ANON_KEY') ?? ''
  const headers = { Authorization: authHeader, apikey: anonKey, 'Content-Type': 'application/json' }
  const requestDeadline = AbortSignal.timeout(90_000)
  const api = (path: string, init?: RequestInit) => fetch(supabaseUrl + path, { ...init, headers, signal: requestDeadline })
  try {
    const userResponse = await api('/auth/v1/user')
    if (!userResponse.ok) return fail('Please sign in again to check papers.', 401)
    const user = await userResponse.json()
    if (!user.id) return fail('Please sign in again to check papers.', 401)
    if (!GEMINI_API_KEY) {
      return Response.json({ error: 'The paper reader is not configured. Contact your administrator.' }, { status: 500, headers: corsHeaders })
    }

    let input: ReturnType<typeof validateReadRequest>
    try {
      if (Number(req.headers.get('content-length') ?? 0) > 7_100_000) return fail('The image is too large.', 413)
      const reader = req.body?.getReader()
      if (!reader) return fail('An image is required.', 400)
      const chunks: Uint8Array[] = []
      let bytes = 0
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        bytes += value.byteLength
        if (bytes > 7_100_000) { await reader.cancel(); return fail('The image is too large.', 413) }
        chunks.push(value)
      }
      const body = new Uint8Array(bytes)
      let offset = 0
      for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.length }
      input = validateReadRequest(JSON.parse(new TextDecoder().decode(body)))
    } catch { return fail('Choose a valid JPEG, PNG, or WebP image smaller than 5 MB.', 400) }
    const { imageBase64, mimeType, sessionId } = input
    const sessionResponse = await api('/rest/v1/checking_sessions?id=eq.' + sessionId + '&select=answer_key_confirmed,rules')
    if (!sessionResponse.ok) return fail('Could not load the checking session.', 503)
    const sessions = await sessionResponse.json()
    if (!sessions[0]?.answer_key_confirmed) return fail('Confirm an authorized answer key before checking papers.', 403)
    const keyResponse = await api('/rest/v1/answer_keys?checking_session_id=eq.' + sessionId + '&select=question_number,question_type,max_points,rubric&order=question_number')
    if (!keyResponse.ok) return fail('Could not load the answer key.', 503)
    const keys: KeyItem[] = await keyResponse.json()
    const totalItems = keys.length
    const rules: string = sessions[0].rules ?? ''
    if (totalItems < 1 || totalItems > 300) return fail('The answer key must contain 1 to 300 questions.', 400)
    const quotaResponse = await api('/rest/v1/rpc/consume_reader_quota', { method: 'POST', body: '{}' })
    if (!quotaResponse.ok) return fail('Could not verify paper-reader usage. Please retry.', 503)
    if (await quotaResponse.json() !== true) return fail('Your paper-reader limit has been reached. Please try again later.', 429)

    // Use the stored, authorized key rather than caller-provided grading instructions.
    const prompt = buildPrompt(totalItems, keys, rules ?? '')

    let response: Response | null = null
    let lastStatus = 0
    for (const model of GEMINI_MODELS) {
      for (let attempt = 0; attempt < 2; attempt++) {
        response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`,
          {
            signal: requestDeadline,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [
                {
                  parts: [
                    { text: prompt },
                    { inline_data: { mime_type: mimeType ?? 'image/jpeg', data: imageBase64 } },
                  ],
                },
              ],
              generationConfig: { maxOutputTokens: 16384, temperature: 0, responseMimeType: 'application/json' },
            }),
          },
        )
        lastStatus = response.status
        if (response.ok) break
        if (response.status === 404) break
        if (response.status === 503) {
          await new Promise((r) => setTimeout(r, 1500))
          continue
        }
        break
      }
      if (response?.ok) break
    }

    if (!response || !response.ok) {
      console.error('Paper reader provider status:', lastStatus)
      return Response.json(
        {
          error: lastStatus === 429
            ? 'You have used up your Gemini API quota. Check your Google AI plan/billing, or try again later.'
            : lastStatus === 503
              ? 'The paper reader is busy. Please try again.'
              : 'The paper reader is unavailable right now.',
        },
        { status: lastStatus === 429 ? 429 : 503, headers: corsHeaders },
      )
    }

    const data = await response.json()
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
    try {
      const match = text.match(/\{[\s\S]*\}/)
      const parsed = JSON.parse(match ? match[0] : text)
      const validated = validateRecognition(parsed, keys.map((k) => k.question_number))
      for (const answer of validated.answers) {
        const key = keys.find((k) => k.question_number === answer.question_number)
        if (answer.points !== undefined && answer.points > (key?.max_points ?? 1)) throw new Error('Points exceed maximum.')
      }
      return Response.json(validated, { headers: corsHeaders })
    } catch {
      console.error('Paper reader returned an invalid response')
      return Response.json({ error: 'Could not understand the answer sheet. Please retake the photo.' }, { status: 422, headers: corsHeaders })
    }
  } catch (e) {
    console.error('Paper reader request failed:', e instanceof Error ? e.name : 'unknown')
    return fail('The paper reader could not complete this request. Check your connection and try again.', 503)
  }
})
